site_name: deepee
nav:
  - Home: index.md
  - FAQ: faq.md
  - Examples: examples.md
  - API: API_reference.md
theme:
  name: material
  palette:
    primary: black
    accent: light blue
  font:
    text: Fira Sans
    mono: Fira Code