name: deepee-examples2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7.0
  - pytorch>=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=10.1
  - scipy
  - torchcsprng
  - pytest
  - mypy
  - black
  - scikit-learn
  - pytorch-lightning
  - matplotlib
  # - albumentations
  - nibabel
  - nilearn
  - bpython
  - ipykernel
  - rope
  - pip
  - pip:
    - testfixtures
    - segmentation-models-pytorch
    - albumentations
    - opacus

